expression -> literal | unary | binary | grouping;

literal  -> NUMBER;
unary    -> ( "-" "+" )? expression;
binary   -> expression operator expression;
grouping -> "(" expression ")";
operator -> "+" "-" "*" "/" "^";
