<number> ::= <digits> ( "." <digits>+ )
<digits> ::= ( "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" )+

<expression>    ::= <term>

<primary>       ::= <number> | <grouping>
<unary>         ::= [ "-" | "+" ] <primary>
<term>          ::= <factor> { ( "+" | "-" ) <factor> }
<factor>        ::= <unary> { ( "*" | "/" ) <unary> }
<grouping>      ::= "(" <term> ")"
